#!/usr/bin/env python3
"""Build browser-loadable JS data files from corpora/*.txt and the
practicalcryptography dictionary file, so index.html can be opened directly
(file://) with no local server and no fetch()/CORS issues."""
import json
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
CORPORA_DIR = os.path.join(ROOT, "corpora")
DICT_FILE = os.path.join(ROOT, "english_words__practicalcryptography_percentile_99.txt")
OUT_DIR = os.path.join(ROOT, "js", "data")
TOP_FRACTION = 0.8


def build_corpora():
    entries = []
    for fname in sorted(os.listdir(CORPORA_DIR)):
        if not fname.endswith(".txt"):
            continue
        path = os.path.join(CORPORA_DIR, fname)
        with open(path, "r") as f:
            text = f.read().strip()
        if not text:
            continue
        entries.append({"file": fname, "text": text})

    os.makedirs(OUT_DIR, exist_ok=True)
    out_path = os.path.join(OUT_DIR, "corpora_data.js")
    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/build_data.py. Do not edit by hand.\n")
        f.write("window.CIPHERGEN_CORPORA = ")
        f.write(json.dumps(entries, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")

    total_chars = sum(len(e["text"]) for e in entries)
    total_words = sum(e["text"].count(" ") + 1 for e in entries)
    print(f"corpora_data.js: {len(entries)} sources, {total_words} words, {total_chars} chars "
          f"({os.path.getsize(out_path)/1024:.0f} KB)")


def build_dictionary():
    words = []
    with open(DICT_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if not parts:
                continue
            w = parts[0]
            if re.match(r"^[A-Z]+$", w):
                words.append(w)

    cutoff = int(len(words) * TOP_FRACTION)
    top_words = words[:cutoff]

    os.makedirs(OUT_DIR, exist_ok=True)
    out_path = os.path.join(OUT_DIR, "dictionary_data.js")
    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/build_data.py. Do not edit by hand.\n")
        f.write("// Top 80% most frequent words (by rank) from english_words__practicalcryptography_percentile_99.txt\n")
        f.write("window.CIPHERGEN_DICTIONARY_TOP80 = ")
        f.write(json.dumps(top_words, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")

    print(f"dictionary_data.js: {len(top_words)}/{len(words)} words "
          f"({os.path.getsize(out_path)/1024:.0f} KB)")


if __name__ == "__main__":
    build_corpora()
    build_dictionary()
